### ISSUE TITLE
`include` path in `install.sh` not updated for new themes folder

### ISSUE THREAD

**Issue by Nathanjms** [bobafetthotmail/refind-theme-regular#28]
I've tried installing this theme, and it seems to not be able to find it after running the install.sh.

After looking at the `install.sh` file, it looks like the line 
```
include refind-theme-regular/theme.conf" | tee -a "${refind_dir}"/refind.conf &> /dev/null
```
on [line 160](https://github.com/bobafetthotmail/refind-theme-regular/blob/master/install.sh#L160) needs updating now the theme is going inside the `themes` folder.

Changing it to 
```
include themes/refind-theme-regular/theme.conf" | tee -a "${refind_dir}"/refind.conf &> /dev/null
```
seemed to fix it on my end, so looks like that's all it needs possibly.

-------
I also had to manually add `themes/` to the beginning of everything in `/boot/efi/EFI/refind/themes/refind-theme-regular/theme.conf`.

This was because the file found at `src/theme.conf`, which is used in `install.sh`, did not account for the new themes directory. I've updated this, as well as the corresponding lines in `install.sh` in the PR below.

**Comment by Nathanjms** [comment]
I also had to manually add `themes/` to the beginning of everything in `/boot/efi/EFI/refind/themes/refind-theme-regular/theme.conf`

I could be wrong, but it seems this is because it overrides the updated `theme.conf` with the older `src/theme.conf` in `install.sh` on [line 192](/boot/efi/EFI/refind/themes/refind-theme-regular/theme.conf), when it runs 
```
cp src/theme.conf theme.conf
```
This older version of theme.conf has not had its directory changed

I was able to fix this second issue more permanently by removing line 192 entirely from the install.sh script - as theme.conf is now kept in the main directory, it does not need to be copied, and running `cp src/theme.conf theme.conf` overrides the newer version.

Unless it's used elsewhere, could you delete src/theme.conf entirely as well as removing that `cp src/theme.conf theme.conf` line to help with this second issue of fonts/image etc not being found

**Comment by bobafetthotmail** [comment]
thanks for taking the time to fix this, I probably should have not accepted the split to a themes folder in the first place to avoid messing with a system that was working fine, but oh well.
