### ISSUE TITLE
Quick question about Icons

### ISSUE THREAD

**Issue by mostwise** [bobafetthotmail/refind-theme-regular#48]
Is there a way to hide unwanted boot options such as the default Linux Penguin or systemd?

**Comment by bobafetthotmail** [comment]
You are asking information about refind functionality, I only maintain a theme and icons for refind.

For future reference, have a look at the relevant page in refind's documentation/website 
https://rodsbooks.com/refind/configfile.html
or ask in the refind support forum on SourceForge https://sourceforge.net/p/refind/discussion/general/
